/* tslint:disable */
/* eslint-disable */
export const __wbg_chain_free: (a: number, b: number) => void;
export const chain_onNotification: (a: number, b: any) => [number, number];
export const chain_transfer: (a: number, b: any) => any;
export const chain_balance: (a: number) => any;
export const chain_identity: (a: number) => any;
export const chain_addOwner: (a: number, b: any, c: number) => any;
export const chain_validatorVersionInfo: (a: number) => any;
export const chain_application: (a: number, b: number, c: number) => any;
export const __wbg_faucet_free: (a: number, b: number) => void;
export const faucet_new: (a: number, b: number) => number;
export const faucet_createWallet: (a: number) => any;
export const faucet_claimChain: (a: number, b: number, c: any) => any;
export const __wbg_client_free: (a: number, b: number) => void;
export const client_new: (a: number, b: any, c: number) => any;
export const client_chain: (a: number, b: any) => any;
export const main: () => void;
export const __wbg_application_free: (a: number, b: number) => void;
export const application_query: (a: number, b: number, c: number, d: number) => any;
export const __wbg_wallet_free: (a: number, b: number) => void;
export const wallet_setOwner: (a: number, b: any, c: any) => any;
export const __web_thread_worker_entry_point: (a: any, b: any) => any;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const intounderlyingsource_cancel: (a: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const __wbg_trap_free: (a: number, b: number) => void;
export const trap___wbg_wasmer_trap: () => void;
export const memory: WebAssembly.Memory;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_5: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_export_7: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h6c108f0cdc15a49a: (a: number, b: number) => void;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h82e53cc2539c8fc5_multivalue_shim: (a: number, b: number) => [number, number];
export const closure3289_externref_shim: (a: number, b: number, c: any) => void;
export const closure3779_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_thread_destroy: (a?: number, b?: number, c?: number) => void;
export const __wbindgen_start: (a: number) => void;
